services:
  backend:
    image: ina-zone-image
    build:
      context: .
    ports:
      - "3000:3000"
  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
